server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 637974700259597
            clientSecret: 1229f0f12ea8fdf246b7a7e73ca56265



  datasource:
    url: ${jdbc:postgresql://ec2-54-234-44-238.compute-1.amazonaws.com:5432/d30059mfrghnqj}
    username: ${ohhmuiywkddkue}
    password: ${71ff5d9a7a82ac7ce9c9919f75a4966d6c9d1c750b252b36f6e83a910917a4b0}
  #    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


