server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 637974700259597
            clientSecret: 1229f0f12ea8fdf246b7a7e73ca56265



  datasource:
    url: ${jdbc:postgres://ec2-54-211-210-149.compute-1.amazonaws.com:5432/d8a9gn2v4u78h4}
    username: ${eqnmseywtoppux}
    password: ${56ee48e2e5f3ec727053c1460c09b4dbdd5bdf285ba66c101fdc436256b6f6b6}
  #    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


