server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

  #  mail:
  #    username: username
  #    password: password
  #    port: 587
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #    host: smtp.gmail.com

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 637974700259597
            clientSecret: 1229f0f12ea8fdf246b7a7e73ca56265



  datasource:
    url: jdbc:postgresql://ec2-54-236-146-234.compute-1.amazonaws.com:5432/d9h2b19aaqv6ih
    username: pmvckqhqdhsioq
    password: 12176682778bb94592786c12c97eb15939bddd7cacfaa38813a2508d7347796a
  #    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml



