server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 637974700259597
            clientSecret: 1229f0f12ea8fdf246b7a7e73ca56265



  datasource:
    url: ${jdbc:postgresql://@ec2-52-204-232-46.compute-1.amazonaws.com:5432/d59jpf55lrm0hh}
    username: ${fnjtywyyptcpep}
    password: ${493ff5586b138e7581a68f298d3fc9b0510b311c780ce0ff78db72179bba12a5}
  #    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


