server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

#  mail:
#    username: username
#    password: password
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    host: smtp.gmail.com

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 637974700259597
            clientSecret: 1229f0f12ea8fdf246b7a7e73ca56265



  datasource:
    url: ${jdbc:postgres://ec2-54-159-138-67.compute-1.amazonaws.com:5432/dcncsdkbepgi75}
    username: ${hcmbujtorvioei}
    password: ${41f188925e1d14d4197dccc43cab04e71a5a9d7f37e0497a90227a345673bc4}
  #    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true


