server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: off

  #  mail:
  #    username: username
  #    password: password
  #    port: 587
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #    host: smtp.gmail.com





  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  #    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml



